### ISSUE TITLE
Let users set the default search engine for the search box

### ISSUE THREAD

**Issue by runical** [the-duck/that-startpage-rocks#2]
Currently, the search engine of the search box defaults to google. It would be very useful to be able to set your own search engine for the normal search.

**Comment by mark-spurgeon** [comment]
Hi @runical , I agree this feature^s missing, thanks :)
It's something I can do quite quickly, I just need to know which search engines need to be added.

Here's a list I made off the top of my head:
- google
- yahoo
- bing 
- duckduckgo

Are there other search engines that would need to be added ?

**Comment by runical** [comment]
Maybe Startpage and IXquick as well? The rest of the list seems to be complete.

**Comment by mark-spurgeon** [comment]
Ok I'll do this, thanks !

**Comment by mark-spurgeon** [comment]
Fixed!

**Comment by runical** [comment]
I saw it on the site. Thanks for this!
